#
# Manifest for PSGet_Manage-FreeIPA module
#
# Generated by: MS-LUF
#
# Generated on : 10/2018
#

@{

# Module de script ou fichier de module binaire associe e ce manifeste
RootModule = 'manage-freeipa.psm1'

# Numero de version de ce module.
ModuleVersion = '0.1'

# editions PS prises en charge
# CompatiblePSEditions = @()

# ID utilise pour identifier de maniere unique ce module
GUID = '2b35c1d3-7f24-484d-b98f-f4a7b2ee6993'

# Auteur de ce module
Author = 'LCU'

# Societe ou fournisseur de ce module
CompanyName = 'lucas-cueff.com'

# Declaration de copyright pour ce module
Copyright = '(c) 2018 lucas-cueff.com Distributed under Artistic Licence 2.0 (https://opensource.org/licenses/artistic-license-2.0).'

# Description de la fonctionnalite fournie par ce module
Description = 'Add few PowerShell cmdlets to manage a FreeIPA server through his JSONRPC web API - https://github.com/freeipa/freeipa'

# Version minimale du moteur Windows PowerShell requise par ce module
PowerShellVersion = '4.0'

# Nom de l'hote Windows PowerShell requis par ce module
# PowerShellHostName = ''

# Version minimale de l'hete Windows PowerShell requise par ce module
# PowerShellHostVersion = ''

# Version minimale du Microsoft .NET Framework requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# DotNetFrameworkVersion = ''

# Version minimale de leenvironnement CLR (Common Language Runtime) requise par ce module. Cette configuration requise est valide uniquement pour PowerShell Desktop Edition.
# CLRVersion = ''

# Architecture de processeur (None, X86, Amd64) requise par ce module
# ProcessorArchitecture = ''

# Modules qui doivent etre importes dans l environnement global prealablement a l importation de ce module
# RequiredModules = @()

# Assemblys qui doivent etre charges prealablement a l importation de ce module
# RequiredAssemblies = @()

# Fichiers de script (.ps1) executes dans l environnement de l appelant prealablement a leimportation de ce module
# ScriptsToProcess = @()

# Fichiers de types (.ps1xml) a charger lors de l importation de ce module
# TypesToProcess = @()

# Fichiers de format (.ps1xml) a charger lors de l importation de ce module
# FormatsToProcess = @()

# Modules a importer en tant que modules imbriques du module specifie dans RootModule/ModuleToProcess
# NestedModules = @()

# Fonctions a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous neavez aucune fonction a exporter.
FunctionsToExport = 'Invoke-FreeIPAAPIPrivilege_Remove_Permission', 'Invoke-FreeIPAAPIPrivilege_Add_Permission', 'Invoke-FreeIPAAPIPermission_Add_Noaci', 'Invoke-FreeIPAAPIPermission_Add_Member', 'Invoke-FreeIPAAPIPermission_Remove_Member','Invoke-FreeIPAAPIPermission_Add', 'Invoke-FreeIPAAPPermission_Del', 'Invoke-FreeIPAAPIPermission_Mod', 'Invoke-FreeIPAAPIPermission_Find', 'Invoke-FreeIPAAPIPermission_Show', 
                    'Invoke-FreeIPAAPIPrivilege_Show', 'Invoke-FreeIPAAPIPrivilege_Find', 'Invoke-FreeIPAAPIPrivilege_Mod', 'Invoke-FreeIPAAPIPrivilege_Add', 'Invoke-FreeIPAAPIPrivilege_Del', 'Invoke-FreeIPAAPIPrivilege_Add_Member', 'Invoke-FreeIPAAPIPrivilege_Remove_Member',
                    'Invoke-FreeIPAAPIRole_Add_Privilege', 'Invoke-FreeIPAAPIRole_Remove_Privilege', 'Invoke-FreeIPAAPIRole_Show', 'Invoke-FreeIPAAPIRole_Find','Invoke-FreeIPAAPIRole_Mod', 'Invoke-FreeIPAAPIRole_Del', 'Invoke-FreeIPAAPIRole_Add', 'Invoke-FreeIPAAPIRole_Add_Member', 'Invoke-FreeIPAAPIRole_Remove_Member',
                    'Invoke-FreeIPAAPIPasswd', 'Invoke-FreeIPAAPIEnv', 
                    'Invoke-FreeIPAAPIUser_Find', 'Invoke-FreeIPAAPIUser_Status', 'Invoke-FreeIPAAPIUser_Add', 'Invoke-FreeIPAAPIUser_Del', 'Invoke-FreeIPAAPIUser_Mod', 'Invoke-FreeIPAAPIUser_Show', 
                    'Invoke-FreeIPAAPIUser_Disable', 'Invoke-FreeIPAAPIUser_Enable', 'Invoke-FreeIPAAPIUser_Unlock', 'Show-IPAUser',
                    'Invoke-FreeIPAAPIConfig_Show', 'Invoke-FreeIPAAPIConfig_Mod', 
                    'Invoke-FreeIPAAPIGroup_Find', 'Invoke-FreeIPAAPIGroup_Mod', 'Invoke-FreeIPAAPIGroup_Remove_Member', 'Invoke-FreeIPAAPIGroup_Del', 'Invoke-FreeIPAAPIGroup_Show', 'Invoke-FreeIPAAPIGroup_Add', 'Invoke-FreeIPAAPIGroup_Add_Member', 
                    'Invoke-FreeIPAAPI', 
                    'Get-FreeIPAAPIAuthenticationCookie', 'Import-FreeIPAAPICrendentials', 'Set-FreeIPAAPICredentials', 'Import-FreeIPAAPICrendentials', 'Invoke-FreeIPAAPISessionLogout', 'Set-FreeIPAAPIServerConfig',
                    'Invoke-FreeIPAAPIHost_Add', 'Invoke-FreeIPAAPIHost_Mod', 'Invoke-FreeIPAAPIHost_Del', 'Invoke-FreeIPAAPIHost_Show', 'Invoke-FreeIPAHost_Find'


# Applets de commande a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas l entree. Utilisez un tableau vide si vous neavez aucune applet de commande e exporter.
CmdletsToExport = @()

# Variables a exporter a partir de ce module
# VariablesToExport = @()

# Alias a exporter a partir de ce module. Pour de meilleures performances, neutilisez pas de caracteres generiques et ne supprimez pas leentree. Utilisez un tableau vide si vous n avez aucun alias a exporter.
AliasesToExport = 'Get-IPAUser', 'Get-IPAUserStatus', 'Find-IPAUser', 'New-IPAUser', 'Set-IPAUser', 'Remove-IPAUser', 'Show-IPAUser',
                    'Enable-IPAUser', 'Disable-IPAUser', 'Unlock-IPAUser', 'Set-IPAUserPassword', 
                    'Show-IPAGroup', 'Get-IPAGroup', 'Find-IPAGroup', 'New-IPAGroup', 'Set-IPAGroup', 'Add-IPAGroupMember', 'Remove-IPAGroupMember', 'Remove-IPAGroup', 
                    'Set-IPACredentials', 'Import-IPACrendentials', 'Import-IPACrendentials', 'Set-IPAServerConfig', 'Import-IPACrendentials', 'Get-IPAAuthenticationCookie', 'Remove-IPAAuthenticationCookie', 
                    'Get-IPAConfig', 'Get-IPAEnvironment', 'Set-IPAConfig', 'Connect-IPA', 'Disconnect-IPA',
                    'Show-IPARole', 'Find-IPARole, Set-IPARole', 'New-IPARole', 'Remove-IPARole', 'Get-IPARole', 'Add-IPARoleMember', 'Remove-IPARoleMember',
                    'Show-IPAPermission', 'Find-IPAPermission', 'Set-IPAPermission', 'New-IPAPermission', 'Remove-IPAPermission', 'Get-IPAPermission', 'Add-IPAPermissionMember', 'Remove-IPAPermissionMember',
                    'Show-IPAPrivilege', 'Find-IPAPrivilege', 'Set-IPAPrivilege', 'New-IPAPrivilege', 'Remove-IPAPrivilege', 'Get-IPAPrivilege', 'Add-IPAPrivilegeMember', 'Remove-IPAPrivilegeMember',
                    'Remove-PrivilegeRole', 'Add-PrivilegeRole', 'Remove-IPAPermissionPrivilege', 'Add-IPAPermissionPrivilege', 'New-IPANoACIPermission',
                    'New-IPAHost', 'Set-IPAHost', 'Remove-IPAHost', 'Show-IPAHost', 'Get-IPAHost', 'Find-IPAHost'

# Ressources DSC a exporter depuis ce module
# DscResourcesToExport = @()

# Liste de tous les modules empaquetes avec ce module
# ModuleList = @()

# Liste de tous les fichiers empaquetes avec ce module
FileList = 'manage-freeipa.psm1'

# Donnees privees a transmettre au module specifie dans RootModule/ModuleToProcess. Cela peut egalement inclure une table de hachage PSData avec des metadonnees de modules supplementaires utilisees par PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('API','FreeIPA','IPA','Kerberos','Ldap','Identity-Management','identity')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MS-LUF/Manage-FreeIPA'

        # A URL to an icon representing this module.
        IconUri = 'https://www.freeipa.org/images/freeipa/freeipa-logo-small.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'v0.1 : connect / disconnect session based on login/password authent mode;Users, hosts, groups (not hostgroup), privilege, permission, role, IPA environnement and IPA config APIs implemented'
        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# URI HelpInfo de ce module
# HelpInfoURI = ''

# Le prefixe par defaut des commandes a ete exporte a partir de ce module. Remplacez le prefixe par defaut a l aide de Import-Module -Prefix.
# DefaultCommandPrefix = ''

}